/**
 * Vector store adapter backed by LanceDB.
 *
 * Stores FeedItems in a LanceDB table and supports semantic vector search
 * in addition to the standard keyword search.  Vectors are generated by a
 * pluggable EmbeddingProvider; if none is configured, the store falls back
 * to keyword search only (searchItems returns undefined).
 *
 * The store also maintains an in-memory index so that structured
 * filtering/sorting (which the query executor handles entirely in JS)
 * remains fast.
 *
 * Directory layout under storagePath/:
 *   <urlHash>/             – LanceDB database directory
 *   <urlHash>/meta.json    – FeedInfo metadata file
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import * as lancedb from "@lancedb/lancedb";
import type { FeedItem, FeedInfo, NativeItem, ObservedFeedSchema } from "../types.js";
import type { RefreshOutcome, StoreAdapter, IngestPair } from "./adapter.js";
import { MemoryStore } from "./index.js";

// ---------------------------------------------------------------------------
// Embedding provider interface
// ---------------------------------------------------------------------------

export interface EmbeddingProvider {
  /** Embed a single string into a float32 vector. */
  embed(text: string): Promise<number[]>;
  /** Dimensionality of the output vector. */
  readonly dimensions: number;
}

/** OpenAI text-embedding-3-small provider. */
export class OpenAIEmbeddingProvider implements EmbeddingProvider {
  readonly dimensions = 1536;
  private client: import("openai").OpenAI | null = null;
  private readonly apiKey: string;
  private readonly model: string;

  constructor(apiKey: string, model = "text-embedding-3-small") {
    this.apiKey = apiKey;
    this.model = model;
  }

  private async getClient(): Promise<import("openai").OpenAI> {
    if (!this.client) {
      const { default: OpenAI } = await import("openai");
      this.client = new OpenAI({ apiKey: this.apiKey });
    }
    return this.client;
  }

  async embed(text: string): Promise<number[]> {
    const client = await this.getClient();
    const res = await client.embeddings.create({
      model: this.model,
      input: text.slice(0, 8192),
    });
    return res.data[0].embedding;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function feedDirName(feedUrl: string): string {
  return createHash("sha256").update(feedUrl).digest("hex").slice(0, 16);
}

/** Sanitize a string value for use in a LanceDB WHERE clause. */
function sanitizeWhereValue(value: string): string {
  // Escape single quotes and backslashes to prevent SQL injection
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function buildSearchText(item: FeedItem, native: NativeItem): string {
  const nativeContent = (native["content:encoded"] ?? native["content"] ?? "") as string;
  return [item.title, item.summary, item.contentText, nativeContent].filter(Boolean).join(" ");
}

// ---------------------------------------------------------------------------
// VectorStore
// ---------------------------------------------------------------------------

interface VectorRow {
  id: string;
  feedUrl: string;
  vector: number[];
  /** JSON-serialised internal FeedItem. */
  payload: string;
  /** JSON-serialised native NativeItem. */
  nativePayload: string;
  [key: string]: unknown;
}

/** Return the LanceDB table name for a given vector dimensionality. */
function tableNameForDims(dims: number): string {
  return `items_d${dims}`;
}

export class VectorStore implements StoreAdapter {
  private memory: MemoryStore;
  private dbs = new Map<string, lancedb.Connection>();
  private tables = new Map<string, lancedb.Table>();

  constructor(
    private readonly storagePath: string,
    private readonly maxItems: number,
    private readonly embedder: EmbeddingProvider | null,
  ) {
    this.memory = new MemoryStore(maxItems);
  }

  private async getOrOpenDb(feedUrl: string): Promise<lancedb.Connection> {
    if (this.dbs.has(feedUrl)) return this.dbs.get(feedUrl)!;
    const dir = join(this.storagePath, feedDirName(feedUrl), "lancedb");
    await mkdir(dir, { recursive: true });
    const db = await lancedb.connect(dir);
    this.dbs.set(feedUrl, db);
    return db;
  }

  private async getOrCreateTable(feedUrl: string): Promise<lancedb.Table> {
    if (this.tables.has(feedUrl)) return this.tables.get(feedUrl)!;
    const db = await this.getOrOpenDb(feedUrl);

    // Each dimensionality gets its own table so switching embedders never
    // causes a vector dimension mismatch on an existing table.
    const dims = this.embedder?.dimensions ?? 4;
    const name = tableNameForDims(dims);
    const existingNames = await db.tableNames();

    let table: lancedb.Table;
    if (existingNames.includes(name)) {
      table = await db.openTable(name);
    } else {
      const seed: VectorRow = {
        id: "__seed__",
        feedUrl,
        vector: Array(dims).fill(0) as number[],
        payload: "{}",
        nativePayload: "{}",
      };
      table = await db.createTable(name, [seed]);
    }
    this.tables.set(feedUrl, table);
    return table;
  }

  /** Load persisted metadata from disk into the memory index. */
  async load(feedUrl: string): Promise<void> {
    const metaPath = join(
      this.storagePath,
      feedDirName(feedUrl),
      "meta.json",
    );
    if (!existsSync(metaPath)) return;

    const meta: FeedInfo = JSON.parse(await readFile(metaPath, "utf-8"));
    await this.memory.initFeed(meta.feedUrl, meta.feedTitle);
    const info = await this.memory.getFeedInfo(meta.feedUrl);
    if (info) Object.assign(info, meta);

    // Load items from LanceDB back into the memory index
    try {
      const table = await this.getOrCreateTable(feedUrl);
      const rows = (await table
        .query()
        .where(`id != '__seed__' AND feedUrl = '${sanitizeWhereValue(feedUrl)}'`)
        .toArray()) as VectorRow[];
      const pairs = rows
        .map((r) => {
          try {
            const internal = JSON.parse(r.payload) as FeedItem;
            const native = r.nativePayload
              ? (JSON.parse(r.nativePayload) as NativeItem)
              : {};
            return { internal, native };
          } catch { return null; }
        })
        .filter((p): p is { internal: FeedItem; native: NativeItem } => p !== null);
      if (pairs.length > 0) await this.memory.ingest(feedUrl, pairs);
    } catch {
      // Table may be empty or not yet created; that's fine
    }
  }

  private async writeMeta(feedUrl: string): Promise<void> {
    const info = await this.memory.getFeedInfo(feedUrl);
    if (!info) return;
    const dir = join(this.storagePath, feedDirName(feedUrl));
    await mkdir(dir, { recursive: true });
    await writeFile(
      join(dir, "meta.json"),
      JSON.stringify(info, null, 2),
      "utf-8",
    );
  }

  async initFeed(feedUrl: string, feedTitle: string | null): Promise<void> {
    await this.memory.initFeed(feedUrl, feedTitle);
    await this.writeMeta(feedUrl);
    // Ensure table exists
    await this.getOrCreateTable(feedUrl);
  }

  async ingest(feedUrl: string, incoming: IngestPair[]): Promise<number> {
    const before = new Set(
      (await this.memory.getAllItems(feedUrl)).map((i) => i.id),
    );
    const newCount = await this.memory.ingest(feedUrl, incoming);

    if (newCount > 0 && this.embedder) {
      const table = await this.getOrCreateTable(feedUrl);
      const newPairs = incoming.filter((p) => !before.has(p.internal.id));

      const rows: VectorRow[] = [];
      for (const { internal, native } of newPairs) {
        const text = buildSearchText(internal, native);
        let vector: number[];
        try {
          vector = await this.embedder.embed(text);
        } catch {
          vector = Array(this.embedder.dimensions).fill(0) as number[];
        }
        rows.push({
          id: internal.id,
          feedUrl,
          vector,
          payload: JSON.stringify(internal),
          nativePayload: JSON.stringify(native),
        });
      }
      if (rows.length > 0) await table.add(rows);
    }

    return newCount;
  }

  async recordRefreshAttempt(
    feedUrl: string,
    outcome: RefreshOutcome,
  ): Promise<void> {
    await this.memory.recordRefreshAttempt(feedUrl, outcome);
    await this.writeMeta(feedUrl);
  }

  async updatePollingMeta(
    feedUrl: string,
    pollingEnabled: boolean,
    pollIntervalMs: number | null,
  ): Promise<void> {
    await this.memory.updatePollingMeta(feedUrl, pollingEnabled, pollIntervalMs);
    await this.writeMeta(feedUrl);
  }

  async getFeedInfo(feedUrl: string): Promise<FeedInfo | null> {
    return this.memory.getFeedInfo(feedUrl);
  }

  async getItem(feedUrl: string, id: string): Promise<FeedItem | null> {
    return this.memory.getItem(feedUrl, id);
  }

  async getAllItems(feedUrl: string): Promise<FeedItem[]> {
    return this.memory.getAllItems(feedUrl);
  }

  hasFeed(feedUrl: string): boolean {
    return this.memory.hasFeed(feedUrl);
  }

  async storeObservedSchema(feedUrl: string, schema: ObservedFeedSchema): Promise<void> {
    await this.memory.storeObservedSchema(feedUrl, schema);
    const dir = join(this.storagePath, feedDirName(feedUrl));
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "schema.json"), JSON.stringify(schema, null, 2), "utf-8");
  }

  async getObservedSchema(feedUrl: string): Promise<ObservedFeedSchema | null> {
    return this.memory.getObservedSchema(feedUrl);
  }

  async getNativeItem(feedUrl: string, id: string): Promise<NativeItem | null> {
    return this.memory.getNativeItem(feedUrl, id);
  }

  async getAllNativeItems(feedUrl: string): Promise<NativeItem[]> {
    return this.memory.getAllNativeItems(feedUrl);
  }

  /** Semantic vector search; returns undefined if no embedder is configured. */
  async searchItems(
    feedUrl: string,
    query: string,
    topK: number,
  ): Promise<FeedItem[] | undefined> {
    if (!this.embedder) return undefined;

    let queryVec: number[];
    try {
      queryVec = await this.embedder.embed(query);
    } catch {
      return undefined;
    }

    const table = await this.getOrCreateTable(feedUrl);
    const rows = (await table
      .vectorSearch(queryVec)
      .limit(topK)
      .where(`feedUrl = '${sanitizeWhereValue(feedUrl)}'`)
      .toArray()) as VectorRow[];

    return rows
      .map((r) => {
        try { return JSON.parse(r.payload) as FeedItem; } catch { return null; }
      })
      .filter((i): i is FeedItem => i !== null);
  }

  async close(): Promise<void> {
    this.tables.clear();
    for (const db of this.dbs.values()) {
      try {
        const closeable = db as unknown as { close?: () => Promise<void> };
        if (typeof closeable.close === "function") {
          await closeable.close();
        }
      } catch { /* ignore cleanup errors */ }
    }
    this.dbs.clear();
    await this.memory.close();
  }
}
